### ISSUE TITLE
error libtun2socks

### ISSUE THREAD

**Issue by ahmad137190** [hossinasaadi/sshTunnel-ios#2]
'libtun2socks/tun2socks.h' file not found xcode help me

xcode 14

**Comment by hossinasaadi** [comment]
> tun2socks.h

tun2socks path is :
[BadvpnSwift/tun2socks/tun2socks.h](https://github.com/hossinasaadi/BadvpnSwift/blob/bd8c24597cec3a2a9a522e5357dc7bd39c38cb7c/tun2socks/tun2socks.h)
modify it in your project.
