### ISSUE TITLE
Publishing on AppStore

### ISSUE THREAD

**Issue by arazgholami** [hossinasaadi/sshTunnel-ios#4]
Any plan for publishing on AppStore?

**Comment by hossinasaadi** [comment]
Sure, maybe in next couple weeks.

**Comment by hossinasaadi** [comment]
> Please let me know if I can help in any way. So many people need this right now to get rid of NapsternetV idiots.

Thanks for your offer Araz. The development is finished and I'm testing the app for the next few days, I let you know when it's published in the Appstore.

**Comment by hossinasaadi** [comment]
Hi @arazgholami , app published sooner than expected :)
[SSH VPN - Client for SSH](https://apps.apple.com/us/app/ssh-vpn-client-for-ssh/id6471132702)
Let me know if anything goes wrong.

**Comment by arazgholami** [comment]
> Hi @arazgholami , app published sooner than expected :) [SSH VPN - Client for SSH](https://apps.apple.com/us/app/ssh-vpn-client-for-ssh/id6471132702) Let me know if anything goes wrong.

Wow, awesome :)

First impressions:
- For a unknown reason, only Telegram works over this tunnel. no other app can make connection to server :/
- At least for me, the main reason for new SSH Tunnel app instead of NapesternetV is ad-free experience. Please consider donation system or, premium version for users outside of Iran and maybe free and ad-free version for Iranian users.
- Import and Export configs (with QRCode) would be great.
- Selecting a config before connecting is not so good experience. Default selection for default config, auto-selecting after editing or adding new config would be awesome.

**Comment by hossinasaadi** [comment]
> * For a unknown reason, only Telegram works over this tunnel. no other app can make connection to server :/

Make sure only enable UDPGW if you set it on your server. the app tunnel whole phone, i checked it with different servers.




> * At least for me, the main reason for new SSH Tunnel app instead of NapesternetV is ad-free experience. Please consider donation system or, premium version for users outside of Iran and maybe free and ad-free version for Iranian users.

> * Import and Export configs (with QRCode) would be great.
> * Selecting a config before connecting is not so good experience. Default selection for default config, auto-selecting after editing or adding new config would be awesome.

Because of my schedule, i just released app with minimum options.
In next updates i will consider premium option and other features.
Thanks.

**Comment by hossinasaadi** [comment]
> I tested with two UDP enabled servers with both LTE and WIFI. I’m suspicious of DNS over SSH. Are you sure app uses DNS over SSH instead of system DNS?

yes I’m pretty sure. when connect to ssh server with UDPGW off, it may took 5-10 sec to establish connection. also close target app (instagram or whatsapp) and open it again.

**Comment by arazgholami** [comment]
Okay, it turns out that disabling UDP in the configurations makes it work perfectly; But I guess it will break anything that needs UDP, like WhatsApp calls.

**Comment by Xiechengqi** [comment]
I think it would be better if this app is just used as an ssh tunnel to maintain connections. After starting it, you can configure socks5 in a vpn client app such as shadowrocket. Very clear traffic proxy link
